{
  "submission_id": "S89",
  "user_id": "U1",
  "problem_id": "P11",
  "timestamp": "2025-10-09T05:22:45Z",
  "status": "Running... (Testcase 18)",
  "language": "python",
  "test_results": [
    {
      "test_case_number": 1,
      "status": "runtime_error",
      "message": "Runtime Error: File \"/sandbox/temp/solution.py\", line 1\n    def gcd(a, b):\\n    while b:\\n        a, b = b, a % b\\n    return a\\n\\ntry:\\n    a, b = map(int, input().split())\\n    print(gcd(a, b))\\nexcept (ValueError, IndexError):\\n    pass\n                   ^\nSyntaxError: unexpected character after line continuation character\nCommand exited with non-zero status 1",
      "execution_time": 0.01,
      "memory_usage": 7.7265625,
      "actual_output": "",
      "expected_output": "2",
      "input": "5698 4838\n"
    },
    {
      "test_case_number": 2,
      "status": "runtime_error",
      "message": "Runtime Error: File \"/sandbox/temp/solution.py\", line 1\n    def gcd(a, b):\\n    while b:\\n        a, b = b, a % b\\n    return a\\n\\ntry:\\n    a, b = map(int, input().split())\\n    print(gcd(a, b))\\nexcept (ValueError, IndexError):\\n    pass\n                   ^\nSyntaxError: unexpected character after line continuation character\nCommand exited with non-zero status 1",
      "execution_time": 0.01,
      "memory_usage": 7.7109375,
      "actual_output": "",
      "expected_output": "3",
      "input": "46926 42591\n"
    },
    {
      "test_case_number": 3,
      "status": "runtime_error",
      "message": "Runtime Error: File \"/sandbox/temp/solution.py\", line 1\n    def gcd(a, b):\\n    while b:\\n        a, b = b, a % b\\n    return a\\n\\ntry:\\n    a, b = map(int, input().split())\\n    print(gcd(a, b))\\nexcept (ValueError, IndexError):\\n    pass\n                   ^\nSyntaxError: unexpected character after line continuation character\nCommand exited with non-zero status 1",
      "execution_time": 0.05,
      "memory_usage": 7.8125,
      "actual_output": "",
      "expected_output": "3",
      "input": "1953 192\n"
    },
    {
      "test_case_number": 4,
      "status": "runtime_error",
      "message": "Runtime Error: File \"/sandbox/temp/solution.py\", line 1\n    def gcd(a, b):\\n    while b:\\n        a, b = b, a % b\\n    return a\\n\\ntry:\\n    a, b = map(int, input().split())\\n    print(gcd(a, b))\\nexcept (ValueError, IndexError):\\n    pass\n                   ^\nSyntaxError: unexpected character after line continuation character\nCommand exited with non-zero status 1",
      "execution_time": 0.04,
      "memory_usage": 7.98828125,
      "actual_output": "",
      "expected_output": "1",
      "input": "41906 7297\n"
    },
    {
      "test_case_number": 5,
      "status": "runtime_error",
      "message": "Runtime Error: File \"/sandbox/temp/solution.py\", line 1\n    def gcd(a, b):\\n    while b:\\n        a, b = b, a % b\\n    return a\\n\\ntry:\\n    a, b = map(int, input().split())\\n    print(gcd(a, b))\\nexcept (ValueError, IndexError):\\n    pass\n                   ^\nSyntaxError: unexpected character after line continuation character\nCommand exited with non-zero status 1",
      "execution_time": 0.01,
      "memory_usage": 7.73828125,
      "actual_output": "",
      "expected_output": "1",
      "input": "1 1\n"
    },
    {
      "test_case_number": 6,
      "status": "runtime_error",
      "message": "Runtime Error: File \"/sandbox/temp/solution.py\", line 1\n    def gcd(a, b):\\n    while b:\\n        a, b = b, a % b\\n    return a\\n\\ntry:\\n    a, b = map(int, input().split())\\n    print(gcd(a, b))\\nexcept (ValueError, IndexError):\\n    pass\n                   ^\nSyntaxError: unexpected character after line continuation character\nCommand exited with non-zero status 1",
      "execution_time": 0.01,
      "memory_usage": 7.8984375,
      "actual_output": "",
      "expected_output": "2",
      "input": "48266 6718\n"
    },
    {
      "test_case_number": 7,
      "status": "runtime_error",
      "message": "Runtime Error: File \"/sandbox/temp/solution.py\", line 1\n    def gcd(a, b):\\n    while b:\\n        a, b = b, a % b\\n    return a\\n\\ntry:\\n    a, b = map(int, input().split())\\n    print(gcd(a, b))\\nexcept (ValueError, IndexError):\\n    pass\n                   ^\nSyntaxError: unexpected character after line continuation character\nCommand exited with non-zero status 1",
      "execution_time": 0.01,
      "memory_usage": 7.8125,
      "actual_output": "",
      "expected_output": "2",
      "input": "36782 13032\n"
    },
    {
      "test_case_number": 8,
      "status": "runtime_error",
      "message": "Runtime Error: File \"/sandbox/temp/solution.py\", line 1\n    def gcd(a, b):\\n    while b:\\n        a, b = b, a % b\\n    return a\\n\\ntry:\\n    a, b = map(int, input().split())\\n    print(gcd(a, b))\\nexcept (ValueError, IndexError):\\n    pass\n                   ^\nSyntaxError: unexpected character after line continuation character\nCommand exited with non-zero status 1",
      "execution_time": 0.01,
      "memory_usage": 7.73828125,
      "actual_output": "",
      "expected_output": "50",
      "input": "100 50\n"
    },
    {
      "test_case_number": 9,
      "status": "runtime_error",
      "message": "Runtime Error: File \"/sandbox/temp/solution.py\", line 1\n    def gcd(a, b):\\n    while b:\\n        a, b = b, a % b\\n    return a\\n\\ntry:\\n    a, b = map(int, input().split())\\n    print(gcd(a, b))\\nexcept (ValueError, IndexError):\\n    pass\n                   ^\nSyntaxError: unexpected character after line continuation character\nCommand exited with non-zero status 1",
      "execution_time": 0.01,
      "memory_usage": 7.7734375,
      "actual_output": "",
      "expected_output": "25000",
      "input": "50000 25000\n"
    },
    {
      "test_case_number": 10,
      "status": "runtime_error",
      "message": "Runtime Error: File \"/sandbox/temp/solution.py\", line 1\n    def gcd(a, b):\\n    while b:\\n        a, b = b, a % b\\n    return a\\n\\ntry:\\n    a, b = map(int, input().split())\\n    print(gcd(a, b))\\nexcept (ValueError, IndexError):\\n    pass\n                   ^\nSyntaxError: unexpected character after line continuation character\nCommand exited with non-zero status 1",
      "execution_time": 0.01,
      "memory_usage": 7.7421875,
      "actual_output": "",
      "expected_output": "3",
      "input": "44349 35742\n"
    },
    {
      "test_case_number": 11,
      "status": "runtime_error",
      "message": "Runtime Error: File \"/sandbox/temp/solution.py\", line 1\n    def gcd(a, b):\\n    while b:\\n        a, b = b, a % b\\n    return a\\n\\ntry:\\n    a, b = map(int, input().split())\\n    print(gcd(a, b))\\nexcept (ValueError, IndexError):\\n    pass\n                   ^\nSyntaxError: unexpected character after line continuation character\nCommand exited with non-zero status 1",
      "execution_time": 0.04,
      "memory_usage": 7.671875,
      "actual_output": "",
      "expected_output": "1",
      "input": "49999 1\n"
    },
    {
      "test_case_number": 12,
      "status": "runtime_error",
      "message": "Runtime Error: File \"/sandbox/temp/solution.py\", line 1\n    def gcd(a, b):\\n    while b:\\n        a, b = b, a % b\\n    return a\\n\\ntry:\\n    a, b = map(int, input().split())\\n    print(gcd(a, b))\\nexcept (ValueError, IndexError):\\n    pass\n                   ^\nSyntaxError: unexpected character after line continuation character\nCommand exited with non-zero status 1",
      "execution_time": 0.06,
      "memory_usage": 7.83203125,
      "actual_output": "",
      "expected_output": "1",
      "input": "33119 1740\n"
    },
    {
      "test_case_number": 13,
      "status": "runtime_error",
      "message": "Runtime Error: File \"/sandbox/temp/solution.py\", line 1\n    def gcd(a, b):\\n    while b:\\n        a, b = b, a % b\\n    return a\\n\\ntry:\\n    a, b = map(int, input().split())\\n    print(gcd(a, b))\\nexcept (ValueError, IndexError):\\n    pass\n                   ^\nSyntaxError: unexpected character after line continuation character\nCommand exited with non-zero status 1",
      "execution_time": 0.03,
      "memory_usage": 7.953125,
      "actual_output": "",
      "expected_output": "1",
      "input": "1640 1519\n"
    },
    {
      "test_case_number": 14,
      "status": "runtime_error",
      "message": "Runtime Error: File \"/sandbox/temp/solution.py\", line 1\n    def gcd(a, b):\\n    while b:\\n        a, b = b, a % b\\n    return a\\n\\ntry:\\n    a, b = map(int, input().split())\\n    print(gcd(a, b))\\nexcept (ValueError, IndexError):\\n    pass\n                   ^\nSyntaxError: unexpected character after line continuation character\nCommand exited with non-zero status 1",
      "execution_time": 0.01,
      "memory_usage": 7.82421875,
      "actual_output": "",
      "expected_output": "1",
      "input": "4181 2584\n"
    },
    {
      "test_case_number": 15,
      "status": "runtime_error",
      "message": "Runtime Error: File \"/sandbox/temp/solution.py\", line 1\n    def gcd(a, b):\\n    while b:\\n        a, b = b, a % b\\n    return a\\n\\ntry:\\n    a, b = map(int, input().split())\\n    print(gcd(a, b))\\nexcept (ValueError, IndexError):\\n    pass\n                   ^\nSyntaxError: unexpected character after line continuation character\nCommand exited with non-zero status 1",
      "execution_time": 0.01,
      "memory_usage": 7.78515625,
      "actual_output": "",
      "expected_output": "1",
      "input": "46368 28657\n"
    },
    {
      "test_case_number": 16,
      "status": "runtime_error",
      "message": "Runtime Error: File \"/sandbox/temp/solution.py\", line 1\n    def gcd(a, b):\\n    while b:\\n        a, b = b, a % b\\n    return a\\n\\ntry:\\n    a, b = map(int, input().split())\\n    print(gcd(a, b))\\nexcept (ValueError, IndexError):\\n    pass\n                   ^\nSyntaxError: unexpected character after line continuation character\nCommand exited with non-zero status 1",
      "execution_time": 0.01,
      "memory_usage": 7.8125,
      "actual_output": "",
      "expected_output": "1",
      "input": "14329 3812\n"
    },
    {
      "test_case_number": 17,
      "status": "runtime_error",
      "message": "Runtime Error: File \"/sandbox/temp/solution.py\", line 1\n    def gcd(a, b):\\n    while b:\\n        a, b = b, a % b\\n    return a\\n\\ntry:\\n    a, b = map(int, input().split())\\n    print(gcd(a, b))\\nexcept (ValueError, IndexError):\\n    pass\n                   ^\nSyntaxError: unexpected character after line continuation character\nCommand exited with non-zero status 1",
      "execution_time": 0.01,
      "memory_usage": 7.73828125,
      "actual_output": "",
      "expected_output": "3",
      "input": "12345 6789\n"
    },
    {
      "test_case_number": 18,
      "status": "runtime_error",
      "message": "Runtime Error: File \"/sandbox/temp/solution.py\", line 1\n    def gcd(a, b):\\n    while b:\\n        a, b = b, a % b\\n    return a\\n\\ntry:\\n    a, b = map(int, input().split())\\n    print(gcd(a, b))\\nexcept (ValueError, IndexError):\\n    pass\n                   ^\nSyntaxError: unexpected character after line continuation character\nCommand exited with non-zero status 1",
      "execution_time": 0.05,
      "memory_usage": 7.87890625,
      "actual_output": "",
      "expected_output": "1",
      "input": "45963 35714\n"
    }
  ]
}